version: '3.9'

services:
  database:
    image: mysql
    container_name: yachay-db
    env_file:
      - ./.env.development
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql

  api:
    image: yachay-backend-dev-test
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: yachay-backend-dev-test
    environment:
      PORT: 3001
    ports:
      - 3001:3001
    depends_on:
      - database
    command: bash -c 'while !</dev/tcp/database/3306; do sleep 1; done; yarn dev'
