PUT http://localhost:3001/api/course/details/1
Content-Type: application/json

{
  "idCourse": 99,
  "idCategory": 99,
  "resume": "NodeJS Course Updated",
  "updatedAt": "2019-10-10 00:00:00",
  "language": "en",
  "filesCount": 34,
  "rating": 4.5,
  "price": 9.99,
  "discount": 0.5,
  "benefits": "Benefits Updated",
  "targetPublic": "Target Public Updated",
  "description": "Description Updated"
}
