## Si no funciona con 3001 utiliza 3000
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
  "info": {
    "nameUser": "Ashel",
    "email": "ashel@gmail.com",
    "password": "algarrobina23"
  },
  "details": {
    "lastName": "Vasquez"
  },
  "role": "Alumno"
}
